Feature/compute bonus stats
Wisdomb33r/ffch-admin pull request #283
Opened 2020-09-12 15:57 UTC by Sylvie

2020-09-13 07:58 UTC, Wisdomb33r requested changes

2020-09-13 07:58 UTC, Wisdomb33r commented on src/app/ffbe/caracteristiques-container-display/caracteristiques-container-display.component.ts
> +  @Input() displayPots: boolean = true;
Sonar préfère sans le type `: boolean`

2020-09-13 07:58 UTC, Wisdomb33r commented on src/app/ffbe/caracteristiques-container-display/caracteristiques-container-display.component.ts
> +  public caracFormatee(carac: number, estPourcent: boolean = false): string {
Sonar préfère sans le type `: boolean`

2020-09-13 07:58 UTC, Wisdomb33r commented on src/app/ffbe/caracteristiques-container-display/caracteristiques-container-display.component.ts
> +  public caracFormatee(carac: number, estPourcent: boolean = false): string {
Je pinaille, mais une fonction est une action et devrait commencer par un verbe (Adams te remercie). `formatCarac` ?

2020-09-13 07:58 UTC, Wisdomb33r commented on src/app/ffbe/ffbe.module.ts
> +    CaracteristiquesContainerDisplayComponent
Manque la `,` finale. Ca permet quand on ajoute une ligne de ne pas toucher à la ligne du dessus, limitant ainsi les difficultés de merge en cas de conflit.

2020-09-13 07:58 UTC, Wisdomb33r commented on src/app/ffbe/mappers/character-entry-stats.mapper.spec.ts
> +    const uniteCarac = CharacterEntryStatsMapper.toUniteCarac(character.entries[100000102].stats, unite, character.entries['100000102'].characterEntrySkills);
Le formatage du code ne semble pas avoir été fait, cette ligne n'est pas au même niveau d’indentation que les autres.

2020-09-13 07:59 UTC, Wisdomb33r commented on src/app/ffbe/model/caracteristiques-container.model.ts
> +};
`,` finale en trop

2020-09-13 11:26 UTC, Sylvie commented on src/app/ffbe/caracteristiques-container-display/caracteristiques-container-display.component.ts
> +  @Input() displayPots: boolean = true;
OK

2020-09-13 11:26 UTC, Sylvie commented on src/app/ffbe/caracteristiques-container-display/caracteristiques-container-display.component.ts
> +  public caracFormatee(carac: number, estPourcent: boolean = false): string {
OK

2020-09-13 11:26 UTC, Sylvie commented on src/app/ffbe/caracteristiques-container-display/caracteristiques-container-display.component.ts
> +  public caracFormatee(carac: number, estPourcent: boolean = false): string {
Changé pour `formateCarac()`

2020-09-13 11:26 UTC, Sylvie commented on src/app/ffbe/caracteristiques-container-display/caracteristiques-container-display.component.ts
> +  public caracFormateePourcent(carac: number): string {
Changé aussi ici

2020-09-13 11:26 UTC, Sylvie commented on src/app/ffbe/ffbe.module.ts
> +    CaracteristiquesContainerDisplayComponent
OK

2020-09-13 11:26 UTC, Sylvie commented on src/app/ffbe/mappers/character-entry-stats.mapper.spec.ts
> +    const uniteCarac = CharacterEntryStatsMapper.toUniteCarac(character.entries[100000102].stats, unite, character.entries['100000102'].characterEntrySkills);
OK

2020-09-13 11:26 UTC, Sylvie commented on src/app/ffbe/model/caracteristiques-container.model.ts
> +};
OK

2020-09-14 06:01 UTC, Wisdomb33r approved these changes

2020-09-14 06:01 UTC, merged