#321: Added the "obtainment" checkbox for 8-star units
Wisdomb33r/ffch-admin pull request #324
Opened 2020-09-22 15:29 UTC by Sylvie

... and updated the backend script.

Fixes #321

2020-09-23 06:54 UTC, Wisdomb33r requested changes

2020-09-23 06:54 UTC, Wisdomb33r commented on src/php/unit_awakenings.php
> +  if ($brex_unite->stars < 6 && $brex_unite->stars > 8) {
Je pense que ce test ne peut pas, dans aucune circonstances et dans aucun univers, donner un résultat positif :-)

2020-09-23 07:09 UTC, Sylvie commented on src/php/unit_awakenings.php
> +  if ($brex_unite->stars < 6 && $brex_unite->stars > 8) {
Attends que je sorte mon convecteur temporel!

2020-09-23 08:29 UTC, Wisdomb33r commented on src/php/unit_awakenings.php
> +  if ($brex_unite->stars < 6 && $brex_unite->stars > 8) {
Je te l'ai déjà dis : dès qu'on doit mettre un voyage dans le temps dans une histoire, ça sous-entends "_j'ai plus d'idée_".

2020-09-24 05:55 UTC, Wisdomb33r approved these changes

2020-09-24 05:58 UTC, merged