Feature/335/parse killers for objets
Wisdomb33r/ffch-admin pull request #339
Opened 2020-10-06 17:25 UTC by Sylvie

Fixes #335

2020-10-07 16:35 UTC, Wisdomb33r requested changes

2020-10-07 16:35 UTC, Wisdomb33r commented on src/app/ffbe/objets-display-components/objet-display/objet-display.component.html
> +    <img *ngIf="present && !different" src="../../../../assets/ok.png" class="ffchstatus" alt="OK">
Quadruple `../` ajouté pour un déplacement d'un niveau de profondeur ? J'ai comme un doute...

2020-10-07 16:35 UTC, Wisdomb33r commented on src/app/ffbe/objets-display-components/objet-tueurs-display/objet-tueurs-display.component.ts
> +    return lowercaseName.charAt(0).toUpperCase() + lowercaseName.slice(1);
Please don't... CSS possède une propriété pour ça :-)
`text-transform: capitalize;`
Voir [ici](https://www.tutorialspoint.com/css/css_text-transform.htm).

2020-10-07 16:35 UTC, Wisdomb33r commented on src/app/ffbe/objets-display-components/objet-tueurs-duo-display/objet-tueurs-duo-display.component.ts
> +export class ObjetTueursDuoDisplayComponent implements OnInit {
`ObjetTueursPhysiqueMagiqueDisplayComponent` ?
`ObjetTueursTypesMultiplesDisplayComponent` ?

2020-10-07 16:35 UTC, Wisdomb33r commented on src/app/ffbe/objets-display-components/objet-tueurs-duo-display/objet-tueurs-duo-display.component.html
> +    <div [ngClass]="'objet-tueurs-left'">
wtf ?
Pourquoi demander à Angular de faire une évaluation quand tu peux écrire `<div class="objet-tueurs-left">` ?

2020-10-07 16:44 UTC, Sylvie commented on src/app/ffbe/objets-display-components/objet-tueurs-duo-display/objet-tueurs-duo-display.component.html
> +    <div [ngClass]="'objet-tueurs-left'">
Aucune idée, j'ai copié le code quelque part, alors ça doit aussi être faux ailleurs :-)

2020-10-07 16:51 UTC, Sylvie commented on src/app/ffbe/objets-display-components/objet-tueurs-duo-display/objet-tueurs-duo-display.component.html
> +    <div [ngClass]="'objet-tueurs-left'">
C'est changé

2020-10-07 16:55 UTC, Sylvie commented on src/app/ffbe/objets-display-components/objet-tueurs-duo-display/objet-tueurs-duo-display.component.ts
> +export class ObjetTueursDuoDisplayComponent implements OnInit {
Va pour `ObjetTueursPhysiquesMagiquesDisplayComponent`

2020-10-07 16:59 UTC, Sylvie commented on src/app/ffbe/objets-display-components/objet-tueurs-display/objet-tueurs-display.component.ts
> +    return lowercaseName.charAt(0).toUpperCase() + lowercaseName.slice(1);
Cool! Merci!

2020-10-07 17:00 UTC, Sylvie commented on src/app/ffbe/model/effects/passives/passive-killer-damage-increase-effect.model.ts
> +  getPhysicalKillers(): Tueurs {
OK

2020-10-07 17:02 UTC, Sylvie commented on src/app/ffbe/objets-display-components/objet-display/objet-display.component.html
> +    <img *ngIf="present && !different" src="../../../../assets/ok.png" class="ffchstatus" alt="OK">
J'ai aucune idée de comment les chemins de fichiers sont résolus.
Si ça marche, c'est grave?

2020-10-08 08:24 UTC, Wisdomb33r approved these changes

2020-10-08 08:25 UTC, merged