#348: Added parser for Magnus skills of GLEX units
Wisdomb33r/ffch-admin pull request #374
Opened 2020-12-24 13:24 UTC by Sylvie

The parser itself is straightforward, but the Magnus effect should appear first in the effect list, so that skill effects should be sorted.

2020-12-24 13:25 UTC, Sylvie commented on src/app/ffbe/mappers/skill-mapper.ts
> +          )));
https://www.youtube.com/watch?v=d-diB65scQU

2020-12-25 09:45 UTC, Wisdomb33r requested changes

2020-12-25 09:45 UTC, Wisdomb33r commented on src/app/ffbe/mappers/skill-mapper.ts
> +          )));
Oui mais non. Déjà 2 ternaires c'est illisible et j'en étais pas fier. Mais 4...

2020-12-26 09:39 UTC, Wisdomb33r approved these changes

2020-12-26 09:40 UTC, merged