Feature/380/putting items
Wisdomb33r/ffch-admin pull request #400
Opened 2021-03-23 06:19 UTC by Sylvie

Fixes #380

2021-03-24 14:13 UTC, Wisdomb33r requested changes

2021-03-24 14:13 UTC, Wisdomb33r commented on src/app/ffbe/objets-display-components/objet-elements-triplet-display/objet-elements-triplet-display.component.html
> -                                  [titre]="'Inflictions'"
Étrange, il semble qu'il y avait deux injections de valeurs pour le paramètre `titre`. Et celui que tu as retiré (`Inflictions`) me semble à moi être celui qui aurait dû rester... t'es sûr que c'est `Total` qui doit rester ? D'ailleurs si on a double injection dans un paramètre, j'ai aucune idée si Angular garde la première ou la dernière des valeurs...

2021-03-24 14:13 UTC, Wisdomb33r commented on src/app/ffbe/objets-display-components/objets-comparing-container-display/objets-comparing-container-display.component.html
> +  [ngClass]="objetsContainer.isPresentInFfchDb() && objetsContainer.dbObjet ? 'objet-left' : ''">
La bonne façon d'écrire ce test est :
`[class.objet-left]="objetsContainer.isPresentInFfchDb() && objetsContainer.dbObjet"`
La syntaxe `[ngClass]` fonctionne, mais c'est l'ancienne façon d'écrire. Moins lisible à cause du triplet `? :`

2021-03-24 14:13 UTC, Wisdomb33r commented on src/app/ffbe/services/ffch-client.service.ts
>    public postObjet$(objet: Objet): Observable<any> {
Le `any` devrait être `Objet` puisque tu as changé le type de retour pour `post<Objet>`.

2021-03-24 14:13 UTC, Wisdomb33r commented on src/app/ffbe/services/ffch-client.service.ts
> +  public putObjet$(objet: Objet): Observable<any> {
Le `any` devrait également être ici `Objet`

2021-03-24 14:13 UTC, Wisdomb33r commented on src/app/ffbe/utils/ffbe-utils.spec.ts
> +  it('should compare correctly null and \'false\'', () => {
Ha oui, là l'escape est nécessaire... mais pourquoi avoir mis dans certains tests des double quotes et dans d'autre des single-quotes (avec nécessité d'escapes).... seul un esprit de Lala doit pouvoir répondre à cette question...

2021-03-24 17:01 UTC, Sylvie commented on src/app/ffbe/objets-display-components/objet-elements-triplet-display/objet-elements-triplet-display.component.html
> -                                  [titre]="'Inflictions'"
Hum, j'ai eu des ennuis avec les titres des éléments, je vais

- [ ] Vérifier les titres des boîtes

2021-03-24 17:01 UTC, Sylvie commented on src/app/ffbe/objets-display-components/objets-comparing-container-display/objets-comparing-container-display.component.html
> +  [ngClass]="objetsContainer.isPresentInFfchDb() && objetsContainer.dbObjet ? 'objet-left' : ''">
- [ ] Moderniser la syntaxe

2021-03-24 17:01 UTC, Sylvie commented on src/app/ffbe/services/ffch-client.service.ts
>    public postObjet$(objet: Objet): Observable<any> {
- [ ] Changer signature (2 fois)

2021-03-24 17:01 UTC, Sylvie commented on src/app/ffbe/utils/ffbe-utils.spec.ts
> +  it('should compare correctly null and \'false\'', () => {
L'incohérence est un droit fondamental!

2021-03-24 17:40 UTC, Sylvie commented on src/app/ffbe/model/caracteristiques.model.ts
> +      return false;
J'ai vérifié que les sous-objets (éléments, caractéristiques, ...) existent (avec des valeurs internes nulles) si l'objet de la DB n'a pas de valeurs pour ces champs.

2021-03-24 17:48 UTC, Sylvie commented on src/app/ffbe/objets-display-components/objets-comparing-container-display/objets-comparing-container-display.component.html
> +  [ngClass]="objetsContainer.isPresentInFfchDb() && objetsContainer.dbObjet ? 'objet-left' : ''">
Remarque, tant que les triplets ne sont pas imbriqués, ça reste lisible

2021-03-24 18:00 UTC, Sylvie commented on src/app/ffbe/objets-display-components/objet-elements-triplet-display/objet-elements-triplet-display.component.html
> -                                  [titre]="'Inflictions'"
C'est bien "Total" qu'on veut afficher, sinon ça veut rien dire.
Pour la 2e question, c'est le dernière valeur injectée qui est utilisée.

2021-03-25 10:03 UTC, Wisdomb33r approved these changes

2021-03-25 10:04 UTC, merged