Feature/407/increased stats several weapon types
Wisdomb33r/ffch-admin pull request #418
Opened 2021-04-05 19:45 UTC by Sylvie

Fixes #407

2021-04-07 15:48 UTC, Wisdomb33r requested changes

2021-04-07 15:48 UTC, Wisdomb33r commented on src/app/ffbe/model/effects/passives/passive-equipment-category-elements-resistance-effect.model.ts
> +      return '+' + currentValue + '% de rés. aux éléments';
À remplacer par la notation string template !

2021-04-07 15:48 UTC, Wisdomb33r commented on src/app/ffbe/model/effects/passives/passive-equipment-category-elements-resistance-effect.model.ts
> +    return '+' + currentValue + '% de rés. ' + accumulatedStats.join(', ');
De même, string template pour les pros !

2021-04-07 16:25 UTC, Sylvie commented on src/app/ffbe/model/effects/passives/passive-equipment-category-elements-resistance-effect.model.ts
> +      return '+' + currentValue + '% de rés. aux éléments';
Ah non pas encore des backquotes!

2021-04-09 13:58 UTC, Wisdomb33r approved these changes

2021-04-09 14:17 UTC, merged