#439: Tentative improvement of Enhancements loading times
Wisdomb33r/ffch-admin pull request #447
Opened 2021-05-20 05:46 UTC by Sylvie

This is a draft.

2021-05-21 17:15 UTC, Sylvie commented
Fixes #439 #450

2021-05-21 17:16 UTC, Sylvie commented
Fixes #450

2021-05-22 15:49 UTC, Wisdomb33r requested changes

2021-05-22 15:49 UTC, Wisdomb33r commented on src/app/ffbe/services/characters.service.spec.ts
> +    expect(character.skills.every(skill => FfbeUtils.isNullOrUndefined(skill.skill))).toBeTrue();
Ce test ne teste probablement pas grand chose. Rien ne garanti que nos mocks soient cohérents et que les skills du character `207002017` soient présents dedans. Il faut vérifier avec quelque chose qui ressemble à :
```
expect(skillService.searchForSkillByGumiId).toHaveBeenCalledTimes(0);
```
Il faut peut-être ajouter un `spyOn(skillService, 'searchForSkillByGumiId').and.callThrough();` dans le `// GIVEN` du test

2021-05-22 17:02 UTC, Wisdomb33r approved these changes

2021-05-22 17:02 UTC, merged