#483: Added the AbilityMoraleJaugeEffect SkillEffect
Wisdomb33r/ffch-admin pull request #486
Opened 2021-07-05 05:38 UTC by Sylvie

This handles the new ability to fill the Morale jauge.

Fixes #483 483

2021-07-05 07:17 UTC, Wisdomb33r requested changes

2021-07-05 07:17 UTC, Wisdomb33r commented on src/app/ffbe/model/effects/abilities/ability-morale-jauge-effect.model.ts
> +      if (parameters.length !== 7 || parameters.splice(1).every(value => value === 0)) {
Ce serait pas le test inverse qui devrait être mis ? Tu mets un warning si toutes les valeurs sont à 0... mais ça me paraît être le cas normal. Le test ne devrait-il pas être `parameters.splice(1).some(value => value !== 0)` ?

2021-07-05 07:17 UTC, Wisdomb33r commented on src/app/ffbe/model/effects/abilities/ability-morale-jauge-effect.model.spec.ts
> +    expect(s).toEqual('+650 à la jauge de moral');
Je vote pour une formulation en % car les joueurs n'ont aucune idée de la graduation sur 10'000 unités. De plus la formulation `à la jauge de moral` ne me plaît pas car c'est une jauge à double sens.

Est-ce que `+6.5% de moral en faveur des alliés` ne serait pas plus clair ? En théorie le joueur devrait voir la jauge se déplacer de 6.5% en sa faveur lors de l'utilisation du skill.

2021-07-05 08:34 UTC, Sylvie commented on src/app/ffbe/model/effects/abilities/ability-morale-jauge-effect.model.spec.ts
> +    expect(s).toEqual('+650 à la jauge de moral');
D'accord! 
Faut-il faire quelque chose de spécial pour les valeurs négatives?
Soit on aurait
`-1.5% de moral en faveur des alliés` si on fait rien
ou alors
`+1.5% de moral en faveur des adversaires`
ou alors 
`-1.5% de moral en défaveur des alliés`
Quel est le plus clair?

2021-07-05 08:34 UTC, Sylvie commented on src/app/ffbe/model/effects/abilities/ability-morale-jauge-effect.model.ts
> +      if (parameters.length !== 7 || parameters.splice(1).every(value => value === 0)) {
Lundi méchant!

2021-07-05 09:54 UTC, Wisdomb33r commented on src/app/ffbe/model/effects/abilities/ability-morale-jauge-effect.model.spec.ts
> +    expect(s).toEqual('+650 à la jauge de moral');
Je pense qu'une valeur négative devrait être mise comme erreur (pas warning mais bien au niveau erreur). Il n'y a aucun cas avec valeur négative dans le DM pour le moment. Et ça n'aurait pas de sens de lancer un sort qui baisse le moral des troupes...
Est-ce qu'on raccourci même la formulation à `+1.5% au moral des alliés` ?

2021-07-05 11:10 UTC, Sylvie commented on src/app/ffbe/model/effects/abilities/ability-morale-jauge-effect.model.spec.ts
> +    expect(s).toEqual('+650 à la jauge de moral');
Oui je préfère la formulation courte. 
Bon on peut toujours imaginer un sort qui aurait plusieurs effets positifs et aussi l'effet de baisser le moral des troupes.
On a déjà vu des sorts offensifs taper sur les alliés et adversaires...
Du coup, je propose de gérer le cas `-1.5% au moral des alliés` avec un parameter warning. Ainsi on aurait déjà la formulation "automatique" et on pourrait la modifier si l'effet doit être compris différemment pour les valeurs négatives.

- [ ] Utiliser la formulation `+1.5% au moral des alliés`
- [ ] Gérer le signe pour les valeurs négatives

2021-07-06 09:47 UTC, Sylvie commented on src/app/ffbe/model/effects/abilities/ability-morale-jauge-effect.model.spec.ts
> +    expect(s).toEqual('-3.5% au moral des alliés<br />+4% de moral par allié actif');
Et du coup, on a pas la même formulation dans les deux cas 😞 
Préfères-tu 
> +4% au moral par allié actif 

?

2021-07-06 11:21 UTC, Wisdomb33r approved these changes

2021-07-06 11:54 UTC, merged