Refactor/522/items gils parsers
Wisdomb33r/ffch-admin pull request #524
Opened 2021-08-12 19:53 UTC by Sylvie

Fixes #522

2021-08-15 16:25 UTC, Wisdomb33r requested changes

2021-08-15 16:25 UTC, Wisdomb33r commented on src/app/ffbe/model/effects/passives/passive-gils-while-stealing-effect.model.ts
> +    return `Permet de voler${tauxText} des gils en plus des objets`;  }
Ton accolade fermante est bizarrement placée... sonar n'aime pas...

2021-08-15 16:36 UTC, Sylvie commented on src/app/ffbe/model/effects/passives/passive-gils-while-stealing-effect.model.ts
> +    return `Permet de voler${tauxText} des gils en plus des objets`;  }
Mais qu'il est tâtillon!

2021-08-16 08:30 UTC, Wisdomb33r approved these changes

2021-08-16 09:04 UTC, merged